export const queryKeys = {
  businessSettings: ["businessSettings"] as const,
  categories: ["categories"] as const,
  products: ["products"] as const,
  components: ["components"] as const,
  componentProducts: ["componentProducts"] as const,
  customerProducts: ["customerProducts"] as const,
  discounts: ["customerProducts"] as const,
  suppliers: ["suppliers"] as const,
  supplierPurchaseOrders: ["supplierPurchaseOrders"] as const,
  supplierPurchaseOrderItems: ["supplierPurchaseOrderItems"] as const,
  orders: ["orders"] as const,
  orderItems: ["orderItems"] as const,
  orderProductionSteps: ["orderProductionSteps"] as const,
  workCenters: ["workCenters"] as const,
  customers: ["customers"] as const,
  users: ["users"] as const,
  dashboard: ["dashboard"] as const,
};
